export const SET_SEARCHED_RECIPES = 'SET_SEARCHED_RECIPES';

export const ADD_RECIPE = 'ADD_RECIPE';

export const GET_PLACES = 'GET_PLACES';

export const GET_IMAGES = 'GET_IMAGES';

export const NEW_PLACES = 'GET_PLACES';

export const NEW_IMAGES = 'NEW_IMAGES';

export const GET_MATCHES = 'GET_MATCHES';

export const GET_PROFILE = 'GET_PROFILE';

export const GET_STATUS = 'GET_STATUS';

export const GET_LOCATION_MATCHES = 'GET_LOCATION_MATCHES';

export const GET_LOCATION_DETAILS = 'GET_LOCATION_DETAILS';

export const GET_MATCH_DETAILS = 'GET_MATCH_DETAILS';

export const GET_CURRENT_USER = 'GET_CURRENT_USER';